os:
  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

# about toolset: https://devblogs.microsoft.com/cppblog/stuck-on-an-older-toolset-version-move-to-visual-studio-2015-without-upgrading-your-toolset/
environment:
  toolset: v90
  PYTHON: "C:\\Python36"

platform:
  - x64

configuration:
  - Release

install:
  - cmd: set PATH=%PATH%;%PYTHON%\Scripts\
  - cmd: echo %PATH%
  - "%PYTHON%\\Scripts\\pip.exe install urllib3==1.25.11" # fix for 10.11.2020, probably soon it will be ok to delete it
  - "%PYTHON%\\Scripts\\pip.exe install conan"
  - cmd: conan user # Create the conan data directory
  - cmd: conan --version

build_script:
  - cd %APPVEYOR_BUILD_FOLDER%/conan-recipes
  # I have to define the source-folder to shorten some paths, as windows has limits on number of path characters
  # so instead of conan create, I call 3 steps: source, install and export-pkg
  - conan source conan-itk --source-folder C:\temp
  - conan install conan-itk user/testing -s build_type=%configuration% -s compiler.toolset=%toolset%
  - conan export-pkg conan-itk user/testing --source-folder C:\temp
  - conan remote add artifactory https://mrkonrad.jfrog.io/artifactory/api/conan/tomato
  - conan user -p %JFROG_API_KEY% -r artifactory konradwerys2@gmail.com
  - conan upload itk/*@user/testing -r artifactory --all --confirm
