language: cpp
dist: xenial
osx_image: xcode12

os:
  - linux
  - osx

compiler:
  - gcc

# Blacklist the documentation branch
branches:
  except:
    - gh-pages

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.9
      - g++-4.9
      - doxygen
      - doxygen-doc
      - doxygen-latex
      - doxygen-gui
      - graphviz
      - lcov

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    sudo apt-get remove googletest
    python --version;
    pyenv versions;
    pyenv shell 3.7.1;
    python --version;
    pip --version;
    pip3 --version;
    pip3 install --user conan;
    conan user;
    conan profile new default --detect;
    conan profile update settings.compiler.version=4.9 default;
    conan profile update env.CC=/usr/bin/gcc-4.9 default;
    conan profile update env.CXX=/usr/bin/g++-4.9 default;
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
    pip3 install conan;
    conan user;
    conan profile new default --detect;
    conan profile update settings.compiler=apple-clang default;
    conan profile update settings.compiler.libcxx=libc++ default;
    conan profile update settings.compiler.version=12.0 default;
    fi

script:
  # conan
  - cd ${TRAVIS_BUILD_DIR}/conan-recipes
  - conan create conan-libyaml user/testing -s build_type=Release
  - conan create conan-libyaml user/testing -s build_type=Debug
  - conan remote add artifactory https://mrkonrad.jfrog.io/artifactory/api/conan/tomato
  - conan user -p ${JFROG_API_KEY} -r artifactory konradwerys2@gmail.com
  - conan upload libyaml/0.2.5@user/testing -r artifactory --all