#------------------------------------#
#   Tomato   #
#------------------------------------#

# todo: add win32
# version: '0.9.{build}'

os:
  - Visual Studio 2017
#  - Visual Studio 2015

init:
  - git config --global core.autocrlf input
  # Set build version to git commit-hash
  - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

environment:
  EXE_EXTENDED_NAME: TomatoExe_%APPVEYOR_REPO_TAG_NAME%_Windows_%PLATFORM%

install:
  - git submodule update --init --recursive

platform:
#  - Win32
  - x64

configuration:
#  - Debug
  - Release

before_build:
  - cd ..
  - git clone https://MRKonrad:%GH_PERSONAL_ACCESS_TOKEN%@github.com/MRKonrad/tomato_private
  - cd Tomato
  - dir
  - cd
  - cd ..
  - cd
  - curl -L -O https://www.dropbox.com/s/fu5we0o2j1a4uzt/ITK412_win_x64_install.zip
  - dir
  - cd
  - 7z x -r ITK412_win_x64_install.zip
  - dir
  - cd Tomato
  - cd
  - dir
  - cmake . -Bbin -A%PLATFORM% -DCMAKE_BUILD_TYPE=%CONFIGURATION% -DCMAKE_INSTALL_PREFIX=install
  - cd

build:
  project: bin\Tomato.sln  # path to Visual Studio solution or project
  parallel: true           # enable MSBuild parallel builds
  verbosity: normal        # MSBuild verbosity level {quiet|minimal|normal|detailed}

after_build:
  # install the files
  - cd bin
  - dir
  - cmake --build . --config %CONFIGURATION% --target INSTALL
  - cd ..
  - mkdir deployment
  # FOR DEPLOYMENT
  - echo "Ready to deploy?"
  # change the name of the exe, zip it and copy the zip to the deployment folders
  - cd bin\%CONFIGURATION%\
  - copy TomatoExe.exe %EXE_EXTENDED_NAME%.exe
  - 7z a %EXE_EXTENDED_NAME%.zip %EXE_EXTENDED_NAME%.exe # zip
  - cd ..\..
  - copy bin\%CONFIGURATION%\%EXE_EXTENDED_NAME%.zip deployment\%EXE_EXTENDED_NAME%.zip

test_script:
  # TODO: should I add sth like this? https://github.com/mgerhardy/caveexpress/blob/master/appveyor.yml
  - cd install\tests\
  - TomatoTests.exe
  - cd ..\..

artifacts:
  - path: deployment\*.*

deploy:
  # release: Tomato-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: Nmbbo4JCoK5AuN1ugWmE/c8/BAXlpz8Lb7piWDcAAWnT/GFa7fwL20GbXyU9AZSn
  draft: false
  prerelease: false
  force_update: true
  on:
    appveyor_repo_tag: true        # deploy on tag push only
    configuration: Release
